export default  [
  { manufact: 'Skoda',
    manufactId: 678,
    car: 'Octavia',
    carId: 67,
    engine: 'engineF457SD',
    engineId: 678,
    myFunction: 'Diagnostics',
    myFunctionId: 689,
  },
  { manufact: 'Skoda',
    manufactId: 678,
    car: 'Octavia',
    carId: 67,
    engine: 'engineF457SD',
    engineId: 678,
    myFunction: 'Diagnostics',
    myFunctionId: 689,
  },
  { manufact: 'Skoda',
    manufactId: 678,
    car: 'Fabia',
    carId: 67897,
    engine: 'carsEngine',
    engineId: 111,
    myFunction: 'new feature on Skoda Fabia',
    myFunctionId: 1689,
  },
  { manufact: 'Skoda',
    manufactId: 678,
    car: 'Fabia',
    carId: 67897,
    engine: 'carsEngine',
    engineId: 111,
    myFunction: 'lol1',
    myFunctionId: 123,
  },
  { manufact: 'Skoda',
    manufactId: 678,
    car: 'Fabia',
    carId: 67897,
    engine: 'carsEngine',
    engineId: 111,
    myFunction: 'lol2',
    myFunctionId: 111111111,
  },
  { manufact: 'Skoda',
    manufactId: 678,
    car: 'Fabia',
    carId: 67897,
    engine: 'carsEngine123',
    engineId: 111,
    myFunction: 'lol2',
    myFunctionId: 111111111,
  },
  { manufact: 'Skoda',
    manufactId: 678,
    car: 'Fabia',
    carId: 67897,
    engine: 'carsEngine123',
    engineId: 111,
    myFunction: 'Fab-lul',
    myFunctionId: 111111111,
  },
  { manufact: 'VV',
    manufactId: 678,
    car: 'Fabia',
    carId: 67897,
    engine: 'carsEngine',
    engineId: 111,
    myFunction: 'lol2',
    myFunctionId: 111111111,
  },
  { manufact: 'Skoda',
    car: 'Octavia',
    engine: 'carsEngine',
    myFunction: 'Bomw'
  },
  { manufact: 'VV',
    car: 'Pežot',
    engine: 'carsEngine',
    myFunction: 'Diagnostics'
  },
]
