export default  [
  { manufact: 'Skoda',
    manufactId: 678,
    car: 'Octavia',
    carId: 67,
    engine: 'motorovk23',
    engineId: 678,
    myFunction: 'Diagnostika',
    myFunctionId: 689,
  },
  { manufact: 'Skoda',
    manufactId: 678,
    car: 'Octavia',
    carId: 67,
    engine: 'motorovk23',
    engineId: 678,
    myFunction: 'Diagnostika',
    myFunctionId: 689,
  },
  { manufact: 'Skoda',
    manufactId: 678,
    car: 'Fabia',
    carId: 67897,
    engine: 'motorovka',
    engineId: 111,
    myFunction: 'novinka na fabii',
    myFunctionId: 1689,
  },
  { manufact: 'Skoda',
    manufactId: 678,
    car: 'Fabia',
    carId: 67897,
    engine: 'motorovka',
    engineId: 111,
    myFunction: 'lol1',
    myFunctionId: 123,
  },
  { manufact: 'Skoda',
    manufactId: 678,
    car: 'Fabia',
    carId: 67897,
    engine: 'motorovka',
    engineId: 111,
    myFunction: 'lol2',
    myFunctionId: 111111111,
  },
  { manufact: 'Skoda',
    manufactId: 678,
    car: 'Fabia',
    carId: 67897,
    engine: 'motorovka123',
    engineId: 111,
    myFunction: 'lol2',
    myFunctionId: 111111111,
  },
  { manufact: 'Skoda',
    manufactId: 678,
    car: 'Fabia',
    carId: 67897,
    engine: 'motorovka123',
    engineId: 111,
    myFunction: 'Fab-lul',
    myFunctionId: 111111111,
  },
  { manufact: 'VV',
    manufactId: 678,
    car: 'Fabia',
    carId: 67897,
    engine: 'motorovka',
    engineId: 111,
    myFunction: 'lol2',
    myFunctionId: 111111111,
  },
  { manufact: 'Skoda',
    car: 'Octavia',
    engine: 'motorovka',
    myFunction: 'Bomw'
  },
  { manufact: 'VV',
    car: 'Pežot',
    engine: 'motorovka',
    myFunction: 'Diagnostika'
  },
]
